apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      {{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: {{ .Values.dockerregistry.name }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: Always
          ports:
            - name: vproapp-port
              containerPort: {{ .Values.app.port }}
      initContainers:
        - name: init-mydb
          image: "{{ .Values.initcontainers.dbWaitImage }}:{{ .Values.initcontainers.dbWaitTag }}"
          command: ["sh", "-c", "until nslookup {{ .Values.db.serviceName }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;"]
        - name: init-memcache
          image: "{{ .Values.initcontainers.mcWaitImage }}:{{ .Values.initcontainers.mcWaitTag }}"
          command: ["sh", "-c", "until nslookup {{ .Values.memcached.serviceName }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for memcache; sleep 2; done;"]
