apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.name }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      {{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: {{ .Values.dockerregistry.name }}
      {{- end }}
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image }}:{{ .Values.db.tag }}"
          ports:
            - name: vprodb-port
              containerPort: {{ .Values.db.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db-pass
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
      initContainers:
        - name: busybox
          image: "{{ .Values.initcontainers.dbCleanImage }}:{{ .Values.initcontainers.dbCleanTag }}"
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vpro-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvcName }}
