apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.pvcName }}
  labels:
    app: {{ .Values.db.name }}
spec:
  storageClassName: {{ .Values.db.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storageSize }}
