apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.serviceName }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: vprodb-port
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.memcached.serviceName }}
spec:
  selector:
    app: {{ .Values.memcached.name }}
  ports:
    - port: {{ .Values.memcached.port }}
      targetPort: vpromc-port
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.serviceName }}
spec:
  selector:
    app: {{ .Values.rabbitmq.name }}
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: vpromq01-port
      protocol: TCP
  type: ClusterIP
